/**
 * Regenerates every image the plugin ships:
 *   1. src/render/glyphs.ts — Lucide glyph markup (plus two custom glyphs) for runtime key rendering
 *   2. SVGs in the .sdPlugin folder — action-list icons, default key images, and mute dial images
 *
 * Run with `npm run icons` after changing glyphs or the key design. Output is committed.
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const lucide = join(root, "node_modules/lucide-static/icons");
const pluginDir = join(root, "ai.michaelp.tally.sdPlugin");

// Glyph name → Lucide icon file (or null for a custom glyph defined below).
const LUCIDE: Record<string, string> = {
	mic: "mic",
	"mic-off": "mic-off",
	video: "video",
	"video-off": "video-off",
	hand: "hand",
	"phone-off": "phone-off",
	"message-square": "message-square",
	"message-square-dot": "message-square-dot",
	"screen-share": "screen-share",
	"thumbs-up": "thumbs-up",
	heart: "heart",
	"party-popper": "party-popper",
	laugh: "laugh",
	"audio-lines": "audio-lines",
	timer: "timer",
	users: "users",
};

// Lucide has no surprised face or background-blur glyph; these follow its 24px, 2px-stroke grid.
const CUSTOM: Record<string, string> = {
	wow: [
		`<circle cx="12" cy="12" r="10"/>`,
		`<path d="M9 9.5v.5"/>`,
		`<path d="M15 9.5v.5"/>`,
		`<circle cx="12" cy="15.5" r="2"/>`,
	].join(""),
	blur: [
		`<circle cx="12" cy="10" r="3"/>`,
		`<path d="M7 18.5a5 5 0 0 1 10 0"/>`,
		`<circle cx="12" cy="12" r="10" stroke-dasharray="1.5 3.2"/>`,
	].join(""),
};

function lucideInner(file: string): string {
	const svg = readFileSync(join(lucide, `${file}.svg`), "utf8");
	const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"));
	return inner.replace(/\s*\n\s*/g, "").replace(/\s*\/>/g, "/>");
}

// 1. glyphs.ts
const glyphs: Record<string, string> = { ...CUSTOM };
let glyphCount: number | "existing" = "existing";
if (existsSync(lucide)) {
	for (const [name, file] of Object.entries(LUCIDE)) glyphs[name] = lucideInner(file);

	const sorted = Object.fromEntries(Object.entries(glyphs).sort(([a], [b]) => a.localeCompare(b)));
	glyphCount = Object.keys(glyphs).length;
	writeFileSync(
		join(root, "src/render/glyphs.ts"),
		[
			"// Generated by scripts/icons.ts — do not edit. Glyphs from Lucide (ISC), https://lucide.dev.",
			"",
			`export const GLYPHS = ${JSON.stringify(sorted, null, "\t")} as const;`,
			"",
			"export type GlyphName = keyof typeof GLYPHS;",
			"",
		].join("\n"),
	);
} else {
	console.warn("lucide-static not found; keeping existing src/render/glyphs.ts and regenerating SVG assets only");
}

// 2. SVGs — imported after glyphs.ts is written so the renderer sees the fresh set.
const { KEY_KINDS, OFFLINE_SNAPSHOT, glyphSvg, keySvg, muteDialFeedback, timerFace, visualFor } = await import("../src/render/key");

function svg(path: string, markup: string): void {
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, markup);
}

function removePngs(dir: string, names: readonly string[]): void {
	for (const name of names) {
		rmSync(join(dir, `${name}.png`), { force: true });
		rmSync(join(dir, `${name}@2x.png`), { force: true });
	}
}

for (const kind of KEY_KINDS) {
	const dir = join(pluginDir, "imgs/actions", kind);
	const visual = visualFor(kind, OFFLINE_SNAPSHOT);
	// Action list: white glyph on transparent, per Elgato's guidelines.
	svg(join(dir, "icon.svg"), glyphSvg(visual.glyph, "#FFFFFF"));
	// Default key face before the plugin has drawn anything.
	svg(join(dir, "key.svg"), kind === "timer" ? timerFace(undefined, "offline") : keySvg(visual));
	removePngs(dir, ["icon", "key"]);
}

// Stream Deck+ mute dial: the dial's icon in the app, and the strip shown before the plugin draws.
const muteDir = join(pluginDir, "imgs/actions/mute");
const padded = `<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="-6 -6 36 36">${glyphSvg("mic", "#FFFFFF").replace(/^<svg[^>]*>|<\/svg>$/g, "")}</svg>`;
svg(join(muteDir, "dial.svg"), padded);
const strip = Buffer.from(muteDialFeedback(OFFLINE_SNAPSHOT).face.split(",")[1], "base64").toString();
svg(join(muteDir, "strip.svg"), strip);
removePngs(muteDir, ["dial", "strip"]);

console.log(`glyphs: ${glyphCount}, key kinds: ${KEY_KINDS.length}`);
