/**
 * Regenerates every image the plugin ships:
 *   1. src/render/glyphs.ts — Lucide glyph markup (plus one custom glyph) for runtime key rendering
 *   2. PNGs in the .sdPlugin folder — action-list icons, default key images, category and plugin icons
 *
 * Run with `npm run icons` after changing glyphs or the key design. Output is committed.
 */
import { Resvg } from "@resvg/resvg-js";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const lucide = join(root, "node_modules/lucide-static/icons");
const pluginDir = join(root, "ai.michaelp.teams.sdPlugin");

// Glyph name → Lucide icon file (or null for a custom glyph defined below).
const LUCIDE: Record<string, string> = {
	mic: "mic",
	"mic-off": "mic-off",
	video: "video",
	"video-off": "video-off",
	hand: "hand",
	"phone-off": "phone-off",
	"message-square": "message-square",
	"message-square-dot": "message-square-dot",
	"screen-share": "screen-share",
	"thumbs-up": "thumbs-up",
	heart: "heart",
	"party-popper": "party-popper",
	laugh: "laugh",
	"audio-lines": "audio-lines",
};

// Lucide has no surprised face; this follows its 24px, 2px-stroke grid.
const CUSTOM: Record<string, string> = {
	wow: [
		`<circle cx="12" cy="12" r="10"/>`,
		`<path d="M9 9.5v.5"/>`,
		`<path d="M15 9.5v.5"/>`,
		`<circle cx="12" cy="15.5" r="2"/>`,
	].join(""),
};

function lucideInner(file: string): string {
	const svg = readFileSync(join(lucide, `${file}.svg`), "utf8");
	const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"));
	return inner.replace(/\s*\n\s*/g, "").replace(/\s*\/>/g, "/>");
}

// 1. glyphs.ts
const glyphs: Record<string, string> = { ...CUSTOM };
for (const [name, file] of Object.entries(LUCIDE)) glyphs[name] = lucideInner(file);

const sorted = Object.fromEntries(Object.entries(glyphs).sort(([a], [b]) => a.localeCompare(b)));
writeFileSync(
	join(root, "src/render/glyphs.ts"),
	[
		"// Generated by scripts/icons.ts — do not edit. Glyphs from Lucide (ISC), https://lucide.dev.",
		"",
		`export const GLYPHS = ${JSON.stringify(sorted, null, "\t")} as const;`,
		"",
		"export type GlyphName = keyof typeof GLYPHS;",
		"",
	].join("\n"),
);

// 2. PNGs — imported after glyphs.ts is written so the renderer sees the fresh set.
const { KEY_KINDS, OFFLINE_SNAPSHOT, glyphSvg, keySvg, markSvg, muteDialFeedback, visualFor } = await import(
	"../src/render/key"
);

function png(svg: string, size: number, path: string): void {
	mkdirSync(dirname(path), { recursive: true });
	const image = new Resvg(svg, { fitTo: { mode: "width", value: size } }).render();
	writeFileSync(path, image.asPng());
}

for (const kind of KEY_KINDS) {
	const dir = join(pluginDir, "imgs/actions", kind);
	const visual = visualFor(kind, OFFLINE_SNAPSHOT);
	// Action list: white glyph on transparent, per Elgato's guidelines.
	png(glyphSvg(visual.glyph, "#FFFFFF"), 20, join(dir, "icon.png"));
	png(glyphSvg(visual.glyph, "#FFFFFF"), 40, join(dir, "icon@2x.png"));
	// Default key face before the plugin has drawn anything.
	png(keySvg(visual), 72, join(dir, "key.png"));
	png(keySvg(visual), 144, join(dir, "key@2x.png"));
}

// Stream Deck+ mute dial: the dial's icon in the app, and the strip shown before the plugin draws.
const muteDir = join(pluginDir, "imgs/actions/mute");
const padded = (size: number) =>
	`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="-6 -6 36 36">${glyphSvg("mic", "#FFFFFF").replace(/^<svg[^>]*>|<\/svg>$/g, "")}</svg>`;
png(padded(72), 72, join(muteDir, "dial.png"));
png(padded(144), 144, join(muteDir, "dial@2x.png"));
const strip = Buffer.from(muteDialFeedback(OFFLINE_SNAPSHOT).face.split(",")[1], "base64").toString();
png(strip, 200, join(muteDir, "strip.png"));
png(strip, 400, join(muteDir, "strip@2x.png"));

png(glyphSvg("audio-lines", "#FFFFFF"), 28, join(pluginDir, "imgs/plugin/category-icon.png"));
png(glyphSvg("audio-lines", "#FFFFFF"), 56, join(pluginDir, "imgs/plugin/category-icon@2x.png"));
png(markSvg(), 256, join(pluginDir, "imgs/plugin/marketplace.png"));
png(markSvg(), 512, join(pluginDir, "imgs/plugin/marketplace@2x.png"));

console.log(`glyphs: ${Object.keys(glyphs).length}, key kinds: ${KEY_KINDS.length}`);
